### ISSUE TITLE
ts/app.ts:49:13 - error TS2322

### ISSUE THREAD

**Issue by GunterO** [rmraya/TMXValidator#1]
Hello,

I'm using your application TMXValidator (thanks for that), but ran into a problem when using this setup:
node v16.14.0
openjdk v17.0.2 2022-01-18
typescript v4.5.5
ant v1.10.12

Got this error:
```
ts/app.ts:49:13 - error TS2322: Type 'string | Buffer' is not assignable to type 'Buffer'.
  Type 'string' is not assignable to type 'Buffer'.

49         let ck: Buffer = execFileSync('bin/java', ['--module-path', 'lib', '-m', 'openxliff/com.maxprograms.server.CheckURL', 'http://localhost:8010/ValidationServer'], { cwd: app.getAppPath() });

```
I could fix it by altering line 49 
from: 
`let ck: Buffer = execFileSync('bin/java', ['--module-path', 'lib', '-m', 'openxliff/com.maxprograms.server.CheckURL', 'http://localhost:8010/ValidationServer'], { cwd: app.getAppPath() });
`
to:
`let ck: Buffer = (execFileSync('bin/java', ['--module-path', 'lib', '-m', 'openxliff/com.maxprograms.server.CheckURL', 'http://localhost:8010/ValidationServer'], { cwd: app.getAppPath() }) as Buffer);
`

Regards,
Gunter

**Comment by rmraya** [comment]
Updated dependencies to Java 17 and TypeScript 4.5.5 . Please refresh your code.
